# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_restaurante_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_likes', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntajetotal', models.BigIntegerField()),
                ('perfil_puntuado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='like_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Perfil'),
        ),
        migrations.AddField(
            model_name='likes',
            name='like_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Restaurante'),
        ),
    ]
