# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_auto_20170925_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='Nombre',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=140),
        ),
    ]
