# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_auto_20171006_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
