# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_remove_restaurante_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='created_date',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
