# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0008_restaurante_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='published_date',
        ),
    ]
