# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0009_auto_20171013_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='my_comentario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advisor.Comentarios'),
            preserve_default=False,
        ),
    ]
